# Generated by Django 4.2.7 on 2023-12-03 07:11

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Property',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('address', models.TextField()),
                ('location', models.CharField(max_length=255)),
                ('features', models.TextField()),
                ('image', models.ImageField(default='no-property-photo.jpg', null=True, upload_to='images')),
            ],
            options={
                'verbose_name_plural': 'Properties',
            },
        ),
    ]
