# Generated by Django 4.2.7 on 2023-12-04 19:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_unit_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tenant',
            name='lease_term',
        ),
    ]
